story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story7.urls')),
    path('', include('story8.urls')),
    path('', include('story9.urls')),
    path('story10/', include('story10.urls'))
]

story10/urls.py
from django.urls import path
from . import views

app_name = 'story10'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('confirmation/', views.confirmation, name='confirmation')
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('accordion/', views.accordion, name='accordion'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('book/', views.book, name='book'),
    path('book/like/', views.like, name='like'),
]

story10/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.


class Message(models.Model):
    nama = models.CharField('your name', max_length=120)
    pesan = models.TextField('your message')
    tanggal_dibuat = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Message by " + self.nama

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=120)
    imageLink = models.CharField(max_length=120)
    author = models.CharField(max_length=120)
    id = models.CharField(max_length=120, primary_key=True, unique=True)
    likes = models.IntegerField(default=0)

    class Meta:
        ordering = ('-likes',)

    def __str__(self):
        return self.title

story7/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import Message


class MessageForm(ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Message
        fields = '__all__'
        widgets = {
            'nama': Textarea(attrs={'cols': 40, 'rows': 1}),
            'pesan': Textarea(attrs={'cols': 40, 'rows': 5}),
            'tanggal_dibuat': forms.HiddenInput(),
        }


class ConfirmationForm(forms.Form):
    action = forms.CharField()

story10/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages

# Create your views here.


def log_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/story10/login/')
            else:
                messages.error(request, 'Password doesn\'t match')
        else:
            messages.error(request, 'Username doesn\'t exist')
    return render(request, 'login.html')


def home(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username is already taken')
        elif User.objects.filter(email=email).exists():
            messages.error(request, 'Email is already taken')
        else:
            user = User.objects.create_user(username, email, password)
            return redirect('/story10/login/')
    return render(request, 'index.html')


def log_out(request):
    logout(request)
    return redirect('/story10/')

story7/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Message
from .forms import MessageForm, ConfirmationForm

# Create your views here.

nama = ""
pesan = ""
data_form = MessageForm()


def homepage(request):
    # homepage.nama = ""
    # homepage.pesan = ""
    global nama, pesan, data_form
    data_form = MessageForm()
    homepage.submitted = False
    input_list = Message.objects.all().order_by('tanggal_dibuat').reverse()
    # homepage.form = MessageForm()
    if request.method == 'POST':
        data_form = MessageForm(request.POST)
        if data_form.is_valid():
            nama = data_form.cleaned_data['nama']
            pesan = data_form.cleaned_data['pesan']
            return redirect('/confirmation/')
    else:
        # homepage.form = MessageForm()
        if 'submitted' in request.GET:
            homepage.submitted = True
    return render(request, 'homepage.html', {'form': data_form, 'submitted': homepage.submitted, 'list': input_list})


def confirmation(request):
    if request.method == 'POST':
        response = ConfirmationForm(request.POST)
        if response.is_valid():
            if response.cleaned_data['action'] == 'yes':
                data_form.save()
                return redirect('/?submitted=True')
            elif response.cleaned_data['action'] == 'no':
                return redirect('/')
    return render(request, 'confirmation.html', {'nama': nama, 'pesan': pesan})

story8/views.py
from django.shortcuts import render

# Create your views here.


def accordion(request):
    return render(request, 'story8.html')

story9/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Book
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.


@csrf_exempt
def book(request):
    if request.method == 'POST':
        books = list(Book.objects.values()[:5])
        return HttpResponse(json.dumps(books))
    else:
        return render(request, 'book.html')


@csrf_exempt
def like(request):
    if request.method == 'POST':
        id = request.POST['id']
        title = request.POST['title']
        imageLink = request.POST['imageLink']
        author = request.POST['author']
        book, status = Book.objects.get_or_create(
            id=id, title=title, imageLink=imageLink, author=author)
        # print(book)
        book.likes += 1
        book.save()
        return HttpResponse(book.likes)
        # return render(request, 'book.html')

story10/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Welcome | Sign Up</title>
    <link rel="stylesheet" href="{% static 'bootstrap-modified.css' %}" />
    <link rel="stylesheet" href="{% static 'style10.css' %}" />
</head>

<body>
    <div class="main">
        {% if user.is_authenticated %}
        <p> Hey, {{ user.username }}, looks like you've already signed in. Click <a
                href="{% url 'story10:login' %}">this link</a> to go back to homepage </p>
        {% else %}

        <h1>create account</h1>

        <div class="container">
            <div class="row mt-4">
                <div class="col-lg-4 col-sm-2"></div>
                <form action="" method="POST" class="col-lg-4 col-sm-8 ">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="e-mail" name="email" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-rose mt-3 mb-4" id="signup">sign up</button>
                </form>
                <div class="col-lg-4 col-sm-2"></div>
            </div>
        </div>

        <p>or <a href="{% url 'story10:login' %}">log in</a> if you already have an account</p>

    </div>

    {% for message in messages %}
    <script>
        alert("{{ message }}")
    </script>
    {% endfor %}

    {% endif %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'story10.js' %}"></script>
</body>

</html>

story10/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Welcome</title>
    <link rel="stylesheet" href="{% static 'bootstrap-modified.css' %}" />
    <link rel="stylesheet" href="{% static 'style10.css' %}" />
</head>

<body>

    <div class="main">
        {% if user.is_authenticated %}
        <h1> How's your day, {{ user.username }}? </h1>
        <p class="mt-5">If you ever have a bad day, it doesn't mean you'll have a bad life. Chin up butter cup,
            <br>everything’s gonna be ok.</p>

        <a href="{% url 'story10:logout' %}" class="btn btn-rose mt-5" id="logout" style="color: white;"
            name="logout">Log Out</a>

        {% else %}
        <h1>welcome back!</h1>

        <div class="container">
            <div class="row mt-4">
                <div class="col-lg-4 col-sm-2"></div>
                <form action="" method="POST" class="col-lg-4 col-sm-8 ">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="password" name="password" required>
                    </div>
                    <button type="submit" class="btn btn-rose mt-3 mb-4" id="login">log in</button>
                </form>
                <div class="col-lg-4 col-sm-2"></div>
            </div>
        </div>

        <p>or <a href="{% url 'story10:home' %}">sign up</a> if you don't have an account</p>

        {% for message in messages %}
        <script>
            alert("{{ message }}")
        </script>
        {% endfor %}


        {% endif %}

    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'story10.js' %}"></script>

</body>

</html>

story7/templates/confirmation.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Confirmation</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="{% static 'bootstrap-modified.css' %}" />
</head>

<body>
    <div class="main">
        <div class="container text-center align-middle" style="margin-top: 30vh; ">
            <h3>Hello, {{ nama }}</h3>
            <h3>is it true you want to send this message?</h3>
            <p style="font-size: larger;">"{{ pesan }}"</p><br>
            <form action="" method="POST">
                {% csrf_token %}
                <input class="rejected btn-primary click " type="submit" name="action" value="no" />
                <input class="confirmed btn-primary click" type="submit" name="action" value="yes" />
            </form>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

</html>

story7/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Spread Your Message!</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="{% static 'bootstrap-modified.css' %}" />
</head>

<body>
    <div class="main">
        <div class="container">
            <div class="row" style="background-color: white; min-height: 80vh; margin-top: 4rem;">
                <div class="col-lg-1"></div>
                <div class="col-lg-5 form-area" style="margin-top: 4rem;">
                    <h1>let the world hear <br>your message</h1><br>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                        <b>{{ field.label_tag }}<br></b>
                        {{ field }}<br><br>
                        {% endfor %}
                        <input class="submit" type="submit" value="Submit" class="btn-primary click" />
                    </form>
                </div>
                <div class="col-lg-5 preview-area " style="margin-top: 4rem;">
                    <div class="container-scrollable prev_box text-lg-left text-md-left text-center mb-5">
                        {% for message in list %}
                        <b>
                            <p class="prev_name" style="font-size: 20px;">{{ message.nama }} said</p>
                        </b>
                        <p class="prev_message">"{{ message.pesan}}"</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-1"></div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</body>

</html>

story8/templates/story8.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Accordion</title>
    <link rel="stylesheet" href="{% static 'bootstrap-modified.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
        body {
            background-color: white;
        }

        .accordion-area {
            max-width: 40vw;
        }

        .accordion {
            background-color: #eee;
            color: #444;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            border: none;
            text-align: left;
            outline: none;
            font-size: 15px;
            transition: 0.4s;
        }

        /* .active, */
        .accordion:hover {
            background-color: #ccc;
        }

        .panel {
            padding: 0 18px;
            display: none;
            background-color: white;
            overflow: hidden;
        }
    </style>
</head>

<body>


    <div class="mt-5 pt-5 text-center">
        <h2 style="text-align: center;">Accordion</h2><br>
    </div>
    <div class="container  pb-3 mb-3 accordion-area">

        <div class="accordion-box" id="about">
            <div class="accordion">
                <a class="klikJudul">About</a>
                <button style="margin-left: 71%;" class="up"> Up </button>
                <button class="down"> Down </button>
            </div>

            <div class="panel p-3">
                <p>Ini accordionnya Wening</p>
            </div>
        </div>


        <div class="accordion-box" id="activities">
            <div class="accordion">
                <a class="klikJudul">Activities</a>
                <button style="margin-left: 67%;" class="up"> Up </button>
                <button class="down"> Down </button>
            </div>

            <div class="panel p-3">
                <p>Sibuk pokoknya</p>
            </div>
        </div>


        <div class="accordion-box" id="experiences">
            <div class="accordion">
                <a class="klikJudul">Experiences</a>
                <button style="margin-left: 62%;" class="up"> Up </button>
                <button class="down"> Down </button>
            </div>

            <div class="panel p-3">
                <p>Masih mau nambah pokoknya</p>
            </div>
        </div>


        <div class="accordion-box" id="achievements">
            <div class="accordion">
                <a class="klikJudul">Achievements</a>
                <button style="margin-left: 60%;" class="up"> Up </button>
                <button class="down"> Down </button>
            </div>

            <div class="panel p-3">
                <p>Ini juga masih mau nambah</p>
            </div>
        </div>
    </div>

    <div class="container text-center">
        <h3>Try me!</h3>
        <button class="bg-default"> Default </button>
        <button class="bg-pink"> Pink </button>
        <button class="bg-salmon"> Salmon </button>
        <button class="bg-cream"> Cream </button>
    </div>

    <script>

        $(document).ready(function () {

            $(".accordion").click(function () {

                if ($(event.target).is('button')) {
                    event.preventDefault();
                    return;
                }

                if ($(this).hasClass("active")) {
                    $(this).removeClass("active");
                    $(this).siblings(".panel").slideUp();
                }

                else {
                    $(".accordion").removeClass("active");
                    $(this).addClass("active");
                    $(".panel").slideUp();
                    $(this).siblings(".panel").slideDown();
                };
            });

            $('.up').click(function () {
                var box = $(this).parents('div.accordion-box');
                box.after(box.prev());
            });

            $('.down').click(function () {
                var box = $(this).parents('div.accordion-box');
                box.before(box.next());
            });

            $(".bg-default").click(function () {
                $("body").css("background-color", "#FFFFFF");
                $(".accordion").css("background-color", "#eee");
            });

            $(".bg-pink").click(function () {
                $("body").css("background-color", "#F38C8F");
                $(".accordion").css("background-color", "#F2B8A4");
            });

            $(".bg-salmon").click(function () {
                $("body").css("background-color", "#F2B8A4");
                $(".accordion").css("background-color", "#FFFFFF");
            });

            $(".bg-cream").click(function () {
                $("body").css("background-color", "#F4D2B6");
                $(".accordion").css("background-color", "#F38C8F");
            });

        });

    </script>

</body>

</html>

story9/templates/book.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Books</title>
    <link rel="stylesheet" href="{% static 'bootstrap-modified.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>

<body>

    <div class="container mt-5">
        <h2 align="center">Finding Books With JSON</h2>
        <br>
        <div align="center">
            <input type="text" name="search" id="search" placeholder="Search by book title" class="form-control"><br>
            <button class="btn btn-info" id="top5button" type="button" data-toggle="modal" data-target="#topmodal">View
                top 5 liked
                books</button>
        </div>

        <div class="modal fade" id="topmodal" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Top 5 Liked Books</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Book Title</th>
                                    <th scope="col">Author</th>
                                    <th scope="col">Likes</th>
                                </tr>
                            </thead>
                            <tbody id="topbooks">
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <br>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Book Title</th>
                    <th scope="col">Author</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody id="result">
            </tbody>
        </table>

        </h1>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <script src="{% static 'jquery.cookie.js' %}"></script>

        <script>
            var csrftoken = $.cookie('csrftoken');
            // var weburl = "http://127.0.0.1:8000/book/"
            var weburl = "https://tddnyawening.herokuapp.com/book/"
            $(document).ready(function () {

                $("#search").keyup(function () {
                    var search = document.getElementById('search').value
                    document.getElementById('result').innerHTML = ""
                    console.log(search)
                    $.ajax({
                        type: 'GET',
                        url: "https://www.googleapis.com/books/v1/volumes?q=" + search,
                        weburl: weburl,
                        dataType: 'json',

                        success: function (data) {
                            console.log(data)
                            for (i = 0; i < data.items.length; i++) {
                                var info = data.items[i]
                                console.log(info.id)
                                result.innerHTML += "<tr id='" + info.id + "~" + info.volumeInfo.title + "~" + info.volumeInfo.imageLinks.thumbnail + "~" + info.volumeInfo.authors + "'><td><img height=40px src='" +
                                    info.volumeInfo.imageLinks.thumbnail + "'></td><td>" +
                                    info.volumeInfo.title + "</td><td>" +
                                    info.volumeInfo.authors +
                                    "</td><td><button type='button' class='btn btn-danger like'>&hearts;</button></td></tr>"
                            }
                            $(".like").click(function () {
                                var info = this.parentNode.parentNode.id
                                var raw = info.split("~")
                                if (raw.length < 3) {
                                    raw.push("undefined")
                                }
                                console.log(info)
                                console.log(raw.toString())
                                console.log("ASJFKAFNKJAFNAAAAAAAAAA MASUK")
                                $.ajax({
                                    type: 'POST',
                                    url: weburl + "like/",
                                    // url: weburl,
                                    dataType: "json",
                                    data: {
                                        'id': raw[0],
                                        'title': raw[1],
                                        'imageLink': raw[2],
                                        'author': raw[3],
                                    },
                                    success: function () {
                                        console.log("AAAAAAAAAAAAAAADINAIDNAJDNAJKS")

                                    }
                                })
                            });
                        },
                    });

                });

                $("#top5button").click(function () {
                    document.getElementById('topbooks').innerHTML = ""
                    $.ajax({
                        type: "POST",
                        url: weburl,
                        success: function (res) {
                            var books = JSON.parse(res);
                            console.log(books)
                            for (i = 0; i < books.length; i++) {
                                topbooks.innerHTML += "<tr><td><img height=40px src='" +
                                    books[i].imageLink + "'></td><td>" +
                                    books[i].title + "</td><td>" +
                                    books[i].author + "</td><td>" +
                                    books[i].likes + "</td></tr>"
                            }
                        }

                    });
                });

                function csrfSafeMethod(method) {
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }

                $.ajaxSetup({
                    beforeSend: function (xhr, settings) {
                        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                            xhr.setRequestHeader("X-CSRFToken", csrftoken);
                        }
                    }
                });

            });

        </script>

</body>

</html>